### ISSUE TITLE
Request Complie with skillapi.

### ISSUE THREAD

**Issue by chocolatecraft** [i998979/BossBarHealth#1]
Request Complie with skillapi.
When I use skill to mob and then mob hp decrease to 0. Health bars wasn't disappear when it died.
However. When I normally attack or use magic from skillapi by rightclick its working but I use select from slot quickbar active skill. Health bar wont dissappear

HP bug.
https://i.ibb.co/zV7Qrng/pic.png

Slot quickbar.
https://i.ibb.co/Fqg75bW/pic.png

**Comment by i998979** [comment]
The plugin works based on EntityDamageEvent, so as long as SkillAPI triggers EntityDamageEvent, the boss bar should work properly. The problem here is that the bar isn't disappearing, it is fixed in 4.1.1.
