### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Leymooo** [i998979/BossBarHealth#3]
This Map https://github.com/i998979/BossBarHealth/blob/master/src/main/java/to/epac/factorycraft/bossbarhealth/hpbar/HealthBar.java#L36 causes memory leak.

![image](https://user-images.githubusercontent.com/8667294/121431163-b932a400-c981-11eb-8be6-c495fdd6414f.png)
take attention to **_size_**.

 I took memory dump when 13 players were online.
There are 2337 EntityPlayer objects in memory

![image](https://user-images.githubusercontent.com/8667294/121431900-acfb1680-c982-11eb-86e7-be19621b68a1.png)

There are GC roots to these objects

![image](https://user-images.githubusercontent.com/8667294/121432119-ef245800-c982-11eb-8c59-b18c7c09aeac.png)

2.3K leaked players cause  6GB memory leak
![image](https://user-images.githubusercontent.com/8667294/121432409-4d513b00-c983-11eb-994e-3533e982810e.png)

**Comment by i998979** [comment]
This should be fixed in the latest commit. If you still have the memory leak issue, you may tell me again anytime.
An update will be posted on Spigot very shortly.
