### ISSUE TITLE
[Suggestion] Add "Player Whitelist" and "always showing" settings

### ISSUE THREAD

**Issue by Chris6ix** [i998979/BossBarHealth#4]
Please add a whitelist or something that allows you to specify a player name to then only show the BossbarHealth of that specific player. (Basically like the Entity Type Blacklist, but for players and in whitelist form)

It would also be awesome if you could add a setting that always shows this Bossbar when you are in a certain radius of that player (like for example the vanilla wither Bossbar works)

It's because I have something on my server where I (The Owner) can become a "Boss" which then all players try to kill me for a reward...and I saw your plugin and really like the idea of using it to show my health to everyone as a real Bossbar, but I don't want all the other bossbars (I don't want that everyone sees everyone's health like this...I want to ONLY show my health like this)

**Comment by i998979** [comment]
The use case of this feature is very narrow, and it is not worth spending time coding it. Also, the radius checking can be very resource-consuming as it checks all player's movements every tick, and such checks should always be avoided.

**Comment by Chris6ix** [comment]
Hey :)
I'm going to admit that the use case for this isn't extremely broad, but it is also not very narrow either, as it would allow using the plugin for basically any Minigame where a player would a "public target". Most features of plugins are not used by every single player...so they all don't really have a super broad use case...

I don't think the radius checking is very resource consuming, because the Vanilla Minecraft Bossbar literally works like this, and you can for example easily have a lot of players in the radius of a lot of wither Bosses at the same time to show their Bossbar without causing issues. 
Some plugins like [HoloMobHealth](https://www.spigotmc.org/resources/holomobhealth-display-mob-health-damage-indicator-client-side-javascript-formatting.75975/) also have the ability to show the health of dozens of mobs in a radius at the same time without causing issues.
If properly implemented (For example, only checking every 20 ticks) radius checking really doesn't cause issues.

Please reconsider adding this Feature, as it would be a nice addition to make the plugin useable for Minigames/Events or similar, and I would really love to use your plugin for my server ;)

**Comment by i998979** [comment]
If such features needed to exist, it should be done by the minigame plugin itself but not an external plugin like this one.

Such features can be added but they should come with more use cases. More suggestions are welcomed but they should be able to convince me.
