### ISSUE TITLE
1.21.1 new mobs

### ISSUE THREAD

**Issue by makegodhere** [i998979/BossBarHealth#8]
i cant add translate for new mobs in 1.12.1 - plugin not loading

**Comment by i998979** [comment]
Acknowledged, i will check that this or next week.

**Comment by i998979** [comment]
It is working fine for me
![2024-10-24_10 43 59](https://github.com/user-attachments/assets/9b38a75d-35e4-45e0-8f49-27d6daea5883)
`BOGGED: 'new mobbbbbb'` in `lang.yml`

**Comment by makegodhere** [comment]
> It is working fine for me ![2024-10-24_10 43 59](https://private-user-images.githubusercontent.com/7139370/379525268-9b38a75d-35e4-45e0-8f49-27d6daea5883.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NTQxOTksIm5iZiI6MTcyOTc1Mzg5OSwicGF0aCI6Ii83MTM5MzcwLzM3OTUyNTI2OC05YjM4YTc1ZC0zNWU0LTQ1ZTAtOGY0OS0yN2Q2ZGFlYTU4ODMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjRUMDcxMTM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTc2YjQzYTU4NGFhNDRmMTAxMjdkYTk0ZjRhNGVkZjc2ZjJiZDU2Yjk1MDk3OGMwMTcwZmNlY2U4Y2NlNzEzOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.jgEAgvaNwSyzDRtF2Rgl9ZOjnPH5iB2i43kpFgdGGZQ) `BOGGED: 'new mobbbbbb'` in `lang.yml`

im sorry - mistake in lang naming
all good thank you
